#[test]
fn test_error_outside_git_dir() {
    assert!(true)
}

#[test]
fn test_return_repo_err_for_unknown_remote() {
    // it should catch error
    assert!(true)
}
